# Generated by Django 5.0.4 on 2024-04-07 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortapp', '0002_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_time', models.DateTimeField(auto_now_add=True)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlshortapp.url')),
            ],
        ),
    ]
