# Generated by Django 5.0.4 on 2024-04-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortapp', '0004_clickstats_click_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report', models.DateTimeField(auto_now_add=True)),
                ('suspected_link', models.URLField()),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('phishing', 'Phishing'), ('scam', 'Scam'), ('malicious', 'Malicious'), ('other', 'Other')], max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
